version: '3'
services:
  api:
    build:
      context: .
    environment:
      - FLASK_DEBUG=1
      - REDIS_HOST=db
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    restart: always
  db:
    image: redis:5.0.6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
