apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  labels:
    status: slave
    label: slave
spec:
  containers:
  - name: jnlp
    image: eu.gcr.io/example/jenkins-slave-jnlp:latest
    workingDir: /home/jenkins
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
      privileged: true
    env: {}
    resources:
      requests:
        memory: 4096
        cpu: 4
    volumeMounts: {}
  nodeSelector:
    nodegroup: infrastructure-jenkins-slaves
  volumes: {}
