apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hello-user.fullname" . }}
  labels:
    app: {{ include "hello-user.name" . }}
    chart: {{ include "hello-user.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ include "hello-user.fullname" . }}
  minReplicas: {{ .Values.replicaCount.min }}
  maxReplicas: {{ .Values.replicaCount.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.podAutoscaling.cpu }}