#kubectl create secret docker-registry gcr-secret \
# --docker-username=_json_key \
# --docker-password="$(cat ~/Downloads/business-intelligence-194510-k8s-image-pull-secret.json)" \
# --docker-server=https://eu.gcr.io \
# --docker-email=example@example.com
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.image.pullSecret }}
data:
  .dockerconfigjson: foobar